FROM 22ndtech/ndtech-go-development-workstation
LABEL maintainer="admin@22ndtech.com"

RUN curl -LO https://fastdl.mongodb.org/linux/mongodb-shell-linux-x86_64-ubuntu2004-4.4.2.tgz
RUN tar -xvf mongodb-shell-linux-x86_64-ubuntu2004-4.4.2.tgz --directory=/usr/bin
ENV PATH=/usr/bin/mongodb-linux-x86_64-ubuntu2004-4.4.2/bin:$PATH

WORKDIR /work

ENTRYPOINT [ "/bin/bash", "/usr/bin/entrypoint.bash" ]