FROM 22ndtech/ndtech-k8s-development-workstation
LABEL maintainer="admin@22ndtech.com"

# RUN curl -LO https://downloads.mongodb.com/compass/mongosh-0.6.1-linux.tgz
# RUN tar -xvf mongosh-0.6.1-linux.tgz 
# RUN mv mongosh /usr/bin

RUN curl -LO https://fastdl.mongodb.org/linux/mongodb-shell-linux-x86_64-ubuntu2004-4.4.2.tgz
RUN tar -xvf mongodb-shell-linux-x86_64-ubuntu2004-4.4.2.tgz --directory=/usr/bin
ENV PATH=/usr/bin/mongodb-linux-x86_64-ubuntu2004-4.4.2/bin:$PATH




# RUN apt-get install -y wget
# RUN wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
# RUN apt-get install gnupg
# RUN wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
# RUN echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
# RUN apt update
# RUN apt-get install -y mongodb-org

WORKDIR /work

ENTRYPOINT [ "/bin/bash", "/scripts/pre-entry.sh" ]