FROM 22ndtech/vscode 
LABEL maintainer="admin@22ndtech.com"

WORKDIR /work

RUN /usr/bin/code --user-data-dir /work/user-data-dir --install-extension hashicorp.terraform

ENTRYPOINT [ "/bin/bash", "/usr/bin/entrypoint.bash" ]