FROM 22ndtech/ndtech-k8s-development-workstation 
LABEL maintainer="admin@22ndtech.com"

ENV GITHUB_USER="$GITHUB_USER"
ENV GITHUB_TOKEN="$GITHUB_TOKEN"

ENV REPOSITORY_NAME="ndtech-workstations"
ENV REPOSITORY_URL="https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/22ndtech/${REPOSITORY_NAME}.git"

COPY ./scripts /scripts/

ENTRYPOINT [ "/bin/bash", "/scripts/pre-entry.sh" ]