FROM 22ndtech/ndtech-go-development-workstation 
LABEL maintainer="admin@22ndtech.com"

ENV DO_EXTERNAL_DNS_TOKEN=${DO_EXTERNAL_DNS_TOKEN}

# Install flux2
RUN curl -s https://toolkit.fluxcd.io/install.sh | bash

ENTRYPOINT [ "/bin/bash", "/usr/bin/entrypoint.bash" ]