FROM 22ndtech/ndtech-node-workstation
LABEL maintainer="admin@22ndtech.com"

WORKDIR /work

RUN /usr/bin/code --user-data-dir /vscode-user-data --install-extension svelte.svelte-vscode

ENTRYPOINT [ "/bin/bash", "/usr/bin/entrypoint.bash" ]

EXPOSE 3001
EXPOSE 3002
EXPOSE 3003
EXPOSE 3004
EXPOSE 3005
EXPOSE 3006
EXPOSE 3007
EXPOSE 3008
EXPOSE 3009
EXPOSE 3010