FROM 22ndtech/ndtech-mongo-workstation
LABEL maintainer="admin@22ndtech.com"

RUN curl -LO https://nodejs.org/dist/v14.15.1/node-v14.15.1-linux-x64.tar.xz
RUN tar -xvf node-v14.15.1-linux-x64.tar.xz --directory=/usr/bin
ENV PATH=/usr/bin/node-v14.15.1-linux-x64/bin/:$PATH

RUN npm install -g express-generator-typescript

WORKDIR /work

ENTRYPOINT [ "/bin/bash", "/usr/bin/entrypoint.bash" ]